# Generated by Django 2.1.1 on 2018-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20181007_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0),
        ),
    ]
